services:
  pg_tenis:
    image: postgres:17
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "tenis_data"
    ports:
      - "5432:5432"
    volumes:
      - tenis_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    ports:
      - "8085:80"

volumes:
  tenis_data:
  pgadmindata:
